[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_ENABLED = "false"
  NEXT_PUBLIC_ADSENSE_PUB_ID = "ca-pub-4413078926879014"

[[plugins]]
  package = "@netlify/plugin-nextjs"
